ocaml-flambda/ocaml-jst

asmcomp/cmm_helpers.ml, testsuite/tests/typing-local/partial.ml, testsuite/tests/typing-local/partial.reference
`caml_applyN` needs a region, but this can prevent tail-call optimisation in some cases. This patch adds a runtime check to the slowpath, preserving tail calls when possible. (The new test in `partial.ml` results in a stack overflow without this change)
=> Better tail call behaviour in caml_applyN

testsuite/tests/typing-local/alloc.ml, testsuite/tests/typing-local/alloc.reference, typing/typecore.ml
A missing call to `register_allocation` meant that we were not optimising the allocation of optional arguments.
=> Optimise the allocation of optional arguments

parsing/lexer.mll, testsuite/tests/typing-local/nosyntax.ml
Avoid having different configurations of lexing and parsing by always enabling the local syntax. Using the syntax when the local extension is disabled will still get an error, but from the type-checker.
=> Enable the local keywords even when the local extension is off

testsuite/tests/typing-local/local.ml, testsuite/tests/typing-objects/Tests.ml, typing/btype.ml, typing/btype.mli, typing/ctype.ml, typing/typecore.ml
Add the obvious subtyping relationship between arrows of related modes, including support in `build_subtype`.
=> Add subtyping between arrows of related modes

testsuite/tests/typing-local/local.ml, typing/ctype.ml
Extends moregen to be directional and then allows submoding in co and contravariant positions.
=> Allow submoding during module inclusion checks

testsuite/tests/typing-local/local.ml, typing/typecore.ml
This patch changes the typing of identifiers to check their type before their mode, because in a really nonsensical application the type error is more informative than the mode error. For instance `print_string (local_ ref 42)` now complains that an `int ref` is not a string, instead of giving an escape error.
=> Better error message on nonsense code

lambda/translcore.ml, testsuite/tests/warnings/w68.compilers.reference, testsuite/tests/warnings/w68.ml, typing/tast_mapper.ml, typing/typecore.ml, typing/typedtree.ml, typing/typedtree.mli
Remembers whether warning 68 was enabled when we type a function so that the warning can be controlled by `[@warning]` attributes. I stored the information as part of the existing `partial` information, which is related, so keeping the data won't take any extra space in e.g. cmt files.
=> Allow warning 68 to be controlled by attributes

testsuite/tests/typing-immediate/immediate.ml, typing/typedecl_immediacy.ml
Updates the logic for determining which types are immediate to include empty types such as `type t = |`.  This will close ocaml/ocaml#9975 once I make the equivalent PR upstream.
=> Make empty types immediate

testsuite/Makefile
The status quo is that you can run any of
```
make -C testsuite one DIR=tests/typing-modules
make -C testsuite one TEST=tests/typing-modules/printing.ml
make -C testsuite one LIST=file
```
if you want to run tests, but you have to run
```
make -C testsuite promote DIR=tests/typing-modules
```
if you want to promote new test output.  This PR attempts to update the machinery for `promote` to be the same as the machinery for `one`, so you can now say
```
make -C testsuite promote TEST=tests/typing-modules/printing.ml
make -C testsuite promote LIST=file
```
as well.
This also fixes an issue where `promote` didn't correctly depend on (`lib` and?) `tools`.
---
I'm not 100% confident this is implemented correctly, and I don't know if we have the requisite expertise or if we want to kick this …
=> Allow `make -C testuite promote` to take `TEST` and `LIST` variables

asmcomp/selectgen.ml, bytecomp/bytegen.ml, lambda/lambda.ml, lambda/lambda.mli, lambda/printlambda.ml, lambda/simplif.ml, lambda/translcore.ml, middle_end/closure/closure.ml, middle_end/flambda/flambda_invariants.ml, middle_end/flambda/inline_and_simplify.ml, middle_end/flambda/inlining_transforms.ml, middle_end/printclambda.ml, parsing/builtin_attributes.ml, parsing/builtin_attributes.mli, testsuite/tests/backtrace/names.ml, testsuite/tests/backtrace/names.reference, testsuite/tests/basic-more/tailannots.ml, testsuite/tests/formatting/test_locations.dlocations.ocamlc.reference, testsuite/tests/formatting/test_locations.dno-locations.ocamlc.reference, testsuite/tests/typing-local/local.ml, typing/printtyped.ml, typing/typecore.ml, typing/typecore.mli, typing/typedtree.ml, typing/typedtree.mli
Applications marked [@nontail] are now never tailcalls, even if in tail position, and always preserve backtraces.
Applications marked [@tail] are always tailcalls and must be in tail position. (This is the same as the existing `[@ocaml.tailcall]`, but the syntax is nicer since the annotation is on the application rather than the function being applied)
=> Add [@tail] and [@nontail] annotations on applications to control tailcalls

bytecomp/bytegen.ml, lambda/lambda.ml, lambda/lambda.mli, lambda/printlambda.ml, lambda/simplif.ml, lambda/translclass.ml, lambda/translcomprehension.ml, lambda/translcore.ml, middle_end/closure/closure.ml, middle_end/flambda/closure_conversion.ml, testsuite/tests/typing-local/loop_regions.heap.reference, testsuite/tests/typing-local/loop_regions.ml, testsuite/tests/typing-local/loop_regions.reference, testsuite/tests/typing-local/loop_regions.stack.reference, typing/printtyped.ml, typing/rec_check.ml, typing/tast_iterator.ml, typing/tast_mapper.ml, typing/typecore.ml, typing/typedtree.ml, typing/typedtree.mli, typing/untypeast.ml
This patch changes the local stack region behavior for the body of for loops,
and the body and condition of while loops.  Now, the user may request that no
new stack region is created for these positions, and instead local allocations
happen in the region containing the loop.
This is of limited use in isolation, but is useful with the coming "let mutable"
patch, where we want to allow locals in a loop body to "escape" to mutable
variables declared in the scope containing the loop.
=> Allow use of `local_` to adjust regions for loops.

bytecomp/bytegen.ml, lambda/lambda.ml, lambda/lambda.mli, lambda/matching.ml, lambda/printlambda.ml, lambda/simplif.ml, lambda/translclass.ml, lambda/translcomprehension.ml, lambda/translcore.ml, middle_end/closure/closure.ml, middle_end/flambda/closure_conversion.ml
Pulling in [upstream PR 10090](https://github.com/ocaml/ocaml/pull/10090).
This is needed for let mutable, because it fixes bugs in how `lambda/simplif.ml` deals with mutable variables.  We initially thought we could get away with a small tweak to simplif to prevent a let binding like `let mutable x = .. in ..` from being substituted away.  But there are trickier cases where subsequent non-mutable lets whose bound variable is defined in terms of `x` are themselves substituted away (which is bad, as the programmer wanted the value of `x` at the place it was mentioned).  Preventing that requires tracking which variables are mutable in lambda, which is what this PR does, so we may as well just take all of it.
The backport was mostly straightforward, except that `translcomprehension.ml` …
=> Backport PR 10090

testsuite/tests/typing-local/local.ml, typing/typecore.ml
This patch makes unboxed type constructors avoid using `mode_subcomponent`, so that they can be e.g. passed to tail calls.
=> Improve typing of local unboxed values

testsuite/tests/typing-ocamlc-i/local.compilers.reference, testsuite/tests/typing-ocamlc-i/local.ml, typing/typemod.ml
The `ocamlc -i` mode, which prints the inferred signature of a module, is missing a call to `remove_mode_variables`. This means that the signature that it prints may have more local annotations than the signature that would be inferred by `ocamlc -c` (with no mli file), and this patch makes them agree again.
=> Remove mode variables in ocamlc -i

parsing/builtin_attributes.ml, parsing/builtin_attributes.mli, testsuite/tests/basic-more/tailannots.ml, typing/typecore.ml
This patch adds `[@tail_if_possible]`, which explicitly selects the current default tailcall behaviour (which may change with #40), but is not an error if used outside of tail position.
There is no reason for a programmer to ever write this annotation, since they're better off using `[@tail]` or `[@nontail]`. However, ppx generators such as `ppx_let` that may rely on tail-call behaviour can use this annotation to guarantee the current behaviour is preserved, without having to work out whether a given application is in tail position.
=> Add [@tail hint] annotation to select default behaviour explicitly

boot/menhir/parser.ml, parsing/asttypes.mli, parsing/parser.mly
When `type global_flag` was just in the `.mly` file, Merlin had trouble, as Merlin wants to export the various tokens and nonterminals, but that type is not exportable.  It's easier to have it live in `Asttypes`, and arguably makes more sense, anyway
=> Move `global_flag` to `Asttypes`

.gitignore
Don't know if it's a 4.14 thing, but some build files are not included in the current `.gitignore` file and could be annoying and slowing down vscode.
=> more entries in gitignore

tools/debug_printers, tools/debug_printers.ml
Add some helper files to make it easier to install useful printers when debugging the compiler with ocamldebug.
=> Add debug_printers.ml

boot/menhir/parser.ml, parsing/parser.mly
This information was updated to propagate to `local_` in types and patterns, where it's encoded as an attribute, but not in expressions, where it's encoded as an extension node.  Getting the location information in types and patterns is/was a blocker for some automated refactorings; getting the location information out further should be similarly useful.  I put this against 4.14 since we'll be rolling forward to that soon.
=> Propagate location information to `local_` in expressions

testsuite/tests/typing-local/regression_class_dep.ml, testsuite/tests/typing-local/regression_class_type.ml, typing/ctype.ml, typing/ctype.mli, typing/typemod.ml
`Ctype.nongen` checks that there are no weakly polymorphic variables, before e.g. inferring the module type of a compilation unit that does not have an mli file, or using `module type of`.
With locals, calls to this function must also be accompanied by a call to `Ctype.remove_mode_variables`, which ensures that there are no unresolved mode variables.
One of these calls got lost in the 4.14 merge, causing #65. The fix here is to make `nongen` call `remove_mode_variables` directly so that this can't happen.
(Fixes #65)
=> Ensure that Ctype.nongen always calls remove_mode_variables

driver/compile_common.ml, parsing/builtin_attributes.ml, parsing/builtin_attributes.mli, stdlib/obj.mli, testsuite/tests/warnings/w53.compilers.reference, testsuite/tests/warnings/w53.ml, testsuite/tests/warnings/w53_mli.compilers.reference, testsuite/tests/warnings/w53_mli.mli, typing/typemod.ml
The new system that checks for unused attributes wasn't running on mli files - only ml files.  This fixes that.
A couple other changes were needed:
- There were some unused `[@inline]` attributes in the stdlib that I deleted.
- The check wasn't correctly handling `[@@@deprecated]`, and I hadn't noticed because this is only used in mlis.  Attributes like this, which are not "used" when compiling the modules they appear in but rather by clients of those modules, require special handling.
=> Run "misplaced attributes" check when compiling mlis

.github/workflows/build.yml
This temporarily fixes the linker warning that's causing hundreds of tests to fail in CI for i386. https://github.com/ocaml-flambda/flambda-backend/pull/1014
=> temp fix for linker error

.gitignore
#78 caused `dynlink_compilerlibs.mli`, an empty file, to be left lying around after the build.  This PR adds it to `.gitignore`.
=> Add dynlink_compilerlibs.mli to .gitignore

typing/ctype.ml
Fixes a BUG introduced in https://github.com/ocaml-flambda/ocaml-jst/pull/50
=> Fix wrong raise for global constructor arguments

testsuite/tests/typing-local/crossing.ml, testsuite/tests/typing-local/crossing_64.ml, typing/typecore.ml
This is only safe if we're sure we don't run bytecode on 64-bit platforms.
=> Make immediate64 things mode cross

typing/typeclass.ml, typing/typecore.ml, typing/typedecl.ml, typing/typemod.ml, typing/typetexp.ml, typing/typetexp.mli
It seemed to me that the code for handling type variable environments was distributed across a bunch of space within Typetexp. So I gathered it all together and modularized it. There should be no change in behavior.
This PR comprises 5 commits, each expressing an independent idea. We can pick and choose which one(s) we want to keep.
If this looks good locally, I will upstream.
=> Refactor the treatment of type variables

lambda/translattribute.ml, parsing/ast_invariants.ml, parsing/builtin_attributes.ml, parsing/builtin_attributes.mli, testsuite/tests/warnings/w53.compilers.reference, testsuite/tests/warnings/w53.ml, testsuite/tests/warnings/w53_ppx.ml, testsuite/tests/warnings/w53_with_ppx.compilers.reference, testsuite/tests/warnings/w53_with_ppx.ml
(This replaces #98)
Not all parse trees are created by the parser in the compiler.  There are at least two other possibilities (see [driver/pparse.ml]): 1) the compiler accepts serialized parse trees constructed by other tools, and 2) the compiler can apply rewriters that modify parse trees.  The previous rework of the misplaced attributes check (#44) missed all attributes in case 1 and rewriter-created attributes in case 2.
The first commit in this PR fixes this situation, using the ast invariant checker used by the compiler in cases 1 and 2 to also insert attributes into the table to be tracked for warning 53.  Compared with #98, we don't attempt to give different warnings for rewriter-inserted attributes - this is slightly trickier than I thought because of case 1, and I'd like to get …
=> Fix misplaced attribute warning when using external parser (and some cleanup)

lambda/translcore.ml, lambda/translprim.ml, testsuite/tests/formatting/test_locations.dlocations.ocamlc.reference, testsuite/tests/formatting/test_locations.dno-locations.ocamlc.reference, testsuite/tests/typing-local/local.ml, typing/printtyped.ml, typing/rec_check.ml, typing/tast_iterator.ml, typing/tast_mapper.ml, typing/typeclass.ml, typing/typecore.ml, typing/typedtree.ml, typing/typedtree.mli, typing/typeopt.ml, typing/untypeast.ml
This patch tries to remove `exp_mode` from `typedtree`, which is hotbed for subtle mode bugs. Instead, we only keep `alloc_mode` in some typed expressions where allocations happen.
=> remove exp_mode from typedtree

lambda/transl_array_comprehension.ml, lambda/transl_comprehension_utils.ml, lambda/transl_comprehension_utils.mli, lambda/transl_list_comprehension.ml, testsuite/tests/comprehensions/array_comprehensions_side_effects.ml
This commit adds an `occur` field to `Let_binding` so that it can correctly use `Lvar` or `Lmutvar`. Tiny bonus: fewer allocations from Lvar nodes, because now we just create one.
=> Consistently use Lmutvar or Lvar in comprehensions

.depend, asmcomp/cmm_helpers.ml, compilerlibs/Makefile.compilerlibs, dune, lambda/lambda.ml, lambda/lambda.mli, lambda/printlambda.ml, lambda/translclass.ml, lambda/translcore.ml, lambda/translcore.mli, lambda/translmod.ml, lambda/translmode.ml, lambda/translmode.mli, lambda/translprim.ml, lambda/translprim.mli, middle_end/printclambda_primitives.ml, typing/printtyped.ml, typing/typeclass.ml, typing/typecore.ml, typing/typecore.mli, typing/typedtree.ml, typing/typedtree.mli
This commit fixes several issues introduced by https://github.com/ocaml-flambda/ocaml-jst/pull/100 
- There is a BUG as pointed out below. 
- Related to the BUG, in `lambda.mli` we replace the `alloc_mode` in `Assignment` with `modify_mode`, because this bit is not about where to allocate a new thing, but about whether the block being modified is on heap or potentially on stack. 
- The remaining names for the mode types (`Value_mode`, `alloc_mode`) are still confusing - we have decided a better naming scheme, and I think it's easier to carry that out in the uniqueness PR.
- In `Texp_field`, `Texp_construct` and `Texp_record` we put `alloc_mode` inside `option` - they will be `Some` only when they actually allocate.
- Minor performance improvements: 
- register allocation for `Texp_send` …
=> fix several issues when removing exp_mode

lambda/transl_list_comprehension.ml, testsuite/tests/comprehensions/comprehensions_from_quickcheck.ml, testsuite/tests/comprehensions/list_comprehensions_pure.ml, testsuite/tests/comprehensions/list_comprehensions_side_effects.ml
This fixes the bug that was causing list comprehensions to fail to build with stack allocation enabled, and reenables all the tests
=> Fix `nlocal` in the generated Lambda for list comprehensions

lambda/printlambda.ml, testsuite/tests/basic-modules/anonymous.ocamlc.reference, testsuite/tests/basic-modules/anonymous.ocamlopt.flambda.reference, testsuite/tests/basic-modules/anonymous.ocamlopt.reference, testsuite/tests/basic/patmatch_for_multiple.ml, testsuite/tests/basic/patmatch_split_no_or.ml, testsuite/tests/formatting/test_locations.dlocations.ocamlc.reference, testsuite/tests/formatting/test_locations.dno-locations.ocamlc.reference, testsuite/tests/functors/functors.compilers.reference, testsuite/tests/tmc/readable_output.ml, testsuite/tests/translprim/array_spec.compilers.flat.reference, testsuite/tests/translprim/comparison_table.compilers.reference, testsuite/tests/translprim/module_coercion.compilers.flat.reference, testsuite/tests/translprim/ref_spec.compilers.reference
I'm open to bikeshedding on the syntax (we want to be able to read this nicely!), but I think we should print this somewhere; without it, I was lead astray in thinking two things were the same that weren't.
=> Print `nlocal` in the `-d(raw)lambda` output

typing/env.ml, typing/env.mli, typing/includemod.ml, typing/includemod_errorprinter.ml, typing/mtype.ml, typing/mtype.mli, typing/typemod.ml
This PR contains refactoring and fixes which improve the code around module type lookup and strengthening. While (hopefully) sensible in their own right, the main driver for this work is improving the performance of module type checking in upcoming PRs which rely on the changes in this PR.
=> Refactoring and fixes around module lookup

lambda/translcore.ml, testsuite/tests/warnings/w53.compilers.reference, testsuite/tests/warnings/w53.ml, testsuite/tests/warnings/w53_marshalled.compilers.reference
Currently we're ignoring attributes on lambda with locally abstract types, like:
```
let f1 = fun [@inline] (type a) (x : a) -> x
```
The issue is that the attribute ends up on a `Pexp_newtype` field in the parser, which then gets pushed into the `exp_extra` field on the function in the typed tree, and the translation to lambda wasn't collecting attributes from `exp_extra`.
I've fixed it by just collecting attributes from any `Texp_newtype` nodes in the `exp_extra` list before we call `Translattribute.add_function_attributes` in the translation to lambda.  That function is where we check for attributes like `inline` on functions.
I imagine this is an upstream bug as well, and will make a PR there at some point soon.
=> Handle attributes on lambdas with locally abstract types

testsuite/tests/typing-local/local.ml, typing/typecore.ml, typing/typecore.mli
In short, this patch rejects certain sound-but-weird typings of applications, so that the principal type of an application is less weird. This matters because in certain contexts (particularly, files with no `mli`), the user actually sees the principal type of expressions, so making it not be weird is good.
Specifically, this patch enforces that in a multiple argument application `f a b c d`, then if any of the intermediate partial applications `f`, `f a`, `f a b` and `f a b c` are local, then all subsequent ones must be also.
This does mean that typing can reject more programs than before. In particular, overapplications of functions with local arguments now yield an error:
```
let f (g : local_ string -> int -> (int -> int -> unit)) = g (local_ "a") 2 3 4 [@nontail]
```
yields:
``` …
```
=> Constrain curry modes to increase along applications

typing/typeclass.ml, typing/typecore.ml, typing/typedecl.ml, typing/typemod.ml, typing/typetexp.ml, typing/typetexp.mli
After merging https://github.com/ocaml/ocaml/pull/11912, I incorporated the changes I made there from comments into ocaml-jst. This subsumes #102, although it incorporates @stedolan's comments there.
=> Incorporate upstream comments into type-variable refactor

testsuite/tests/formatting/test_locations.dlocations.ocamlc.reference, testsuite/tests/formatting/test_locations.dno-locations.ocamlc.reference, testsuite/tests/typing-local/local.ml, typing/env.ml, typing/env.mli, typing/typeclass.ml, typing/typecore.ml, typing/typecore.mli, typing/typemod.ml
During type checking there were several places where the returning value's mode can be relaxed to `local`, thus making mode checking faster.
=> Replace var with local for faster mode checking

.gitignore, .ocaml-bin, Makefile.common-jst, jane-street-merlin-setup.sh, jenga.conf
Now Jane Street internal developers can get Merlin within the compiler when building with `dune`.
Once we improve the internal tooling in a couple of ways (see comments) we can simplify some of the way this is done.
@stedolan: Why is `dune-project` only created from `dune-project.jst`?
=> Enable support for Jane Street's internal Merlin configuration

HACKING.jst.adoc, tools/debug_printers, tools/debug_printers.ml, typing/ctype.ml, typing/ctype.mli
This PR adds a way of printing some of `Ctype`'s global state (including current level), and adds the debug printer to the set of printers installed by `tools/debug_printers`.
Output from `ocamldebug`:
```ocaml
(ocd) p Ctype.global_state
Ctype.global_state: Ctype.global_state =
{current_level = 2; nongen_level = 2; global_level = 2}
```
=> Add Ctype global state debug printers

.depend, boot/menhir/parser.ml, parsing/ast_mapper.ml, parsing/ast_mapper.mli, parsing/extensions.ml, parsing/extensions.mli, parsing/extensions_parsing.ml, parsing/extensions_parsing.mli, parsing/parser.mly, typing/parmatch.ml, typing/untypeast.ml
This also tweaks the `Ast_mapper` types for modular extension nodes to be more uniform
=> Change modular extensions to produce `AST_desc` types

.gitignore, .ocaml-bin, jane-street-merlin-setup.sh, jenga.conf
This removes hacky code that we think was breaking with Emacs changes.
=> Fully switch over Jane Street Merlin support to `.local-*`

typing/includemod.ml, typing/mtype.mli
We were calling `expand_module_alias` to get the unstrengthened, non-lazy type (potential deep copy), then checking whether it's an ident and then strengthening it, thus throwing most of it away. This patch avoids doing that by working directly on the lazy representation. This substantially reduces the peak heap size (and improves compile times, albeit to a lesser degree) in some cases.
Note that https://github.com/ocaml-flambda/ocaml-jst/pull/119 changes this area significantly so I didn't want to refactor too much here.
=> Don't copy when resolving aliases in try_modtypes

parsing/extensions_parsing.ml, parsing/extensions_parsing.mli, testsuite/tests/jst-modular-extensions/user_error2.compilers.reference
This worsens the error message in a case that should never arise in practice, but it simplifies the process for adding new AST types.
=> Remove raw_body from modular extensions setup

ocamldoc/Makefile, ocamldoc/odoc_sig.ml, parsing/ast_iterator.ml, parsing/ast_iterator.mli, parsing/ast_mapper.ml, parsing/ast_mapper.mli, parsing/depend.ml, parsing/extensions.ml, parsing/extensions.mli, parsing/extensions_parsing.ml, parsing/extensions_parsing.mli, parsing/parsetree.mli, parsing/pprintast.ml, parsing/printast.ml, tools/lintapidiff.ml, typing/typemod.ml
This doesn't actually support strengthening, but just lays the groundwork for doing so. For strengthening support, wait for the next PR, coming up soon.
=> Add support for extensions in module types

ocamldoc/odoc_sig.ml, parsing/ast_iterator.ml, parsing/ast_mapper.ml, parsing/depend.ml, parsing/extensions.ml, parsing/extensions.mli, parsing/pprintast.ml, typing/typemod.ml, utils/language_extension.ml, utils/language_extension.mli
This should set the stage for a rebase of #119. Note that there are 4 new `failwith`s I added for @rleshchinskiy to fill in.
(This has not been adequately tested, as I'm on my personal computer on a train. But CI should fill in that gap. I know the code compiles and passes most tests.)
=> Add a Strengthen extension

Makefile.common-jst, testsuite/Makefile, testsuite/summarize.awk
This target promotes all tests that failed on the previous run; it's good for after running `make -C testsuite parallel`, for example.
If this looks good here I'll also send it upstream separately.
(This is the awkified, Makefileified version of my little shell script
```
for test in $(awk -f testsuite/summarize.awk < testsuite/_log  | perl -ne 'print if /List of failed tests/../^$/ and s/^\s+(tests\/\S+) with \d.+/$1/'); do make -C testsuite promote TEST="$test"; done
```
)
=> Add `promote-failed` targets to the Makefiles

.gitignore, HACKING.jst.adoc, tools/Makefile, tools/debug_printers
This cherry-picks a generally applicable improvement from antalsz#3 so that we can just edit `tools/debug_printers.ml`, rather than two separate files, and then `make -C tools debug_printers` to build.
=> Autogenerate tools/debug_printer

typing/typecore.ml
This PR is a clone of https://github.com/ncik-roberts/ocaml-jst/pull/1 --- things got in a bad state upon trying to merge that PR into the `typedtree-module-patterns` branch, and I found it most convenient to pull the commits out into a new PR against main. See that PR for discussion.
This PR indeed has the same diff as the already-reviewed PR; run this to confirm:
```
$ diff <(git diff af24f25 247163a) <(git diff 3825013 c8367c0)
```
=> Remove `type_unpacks`

dune
Strike `-absname` from dune builds. This means that (when we build the compiler) we'll get error messages like:
```
File "typing/typecore.ml", line 3888, characters 6-8:
Error: This pattern matches values of type unit
but a pattern was expected which matches values of type int
```
instead of error messages like:
```
File "/usr/local/home/nroberts/ocaml/nroberts/_build/default/typing/typecore.ml", line 3888, characters 6-8:
Error: This pattern matches values of type unit
but a pattern was expected which matches values of type int
```
This has better compatibility with e.g. emacs `compile`.
* Old behavior: jumping to next error brought you to the `_build` directory
* New behavior: jumping to next error brings you to the file you care about
=> Remove `-absname` to improve dune build errors

Makefile.common-jst
`make -f Makefile.jst install` now also puts `ocamlc` at the root of the repo. It's recommended to run `ocamldebug` on it rather than the one in `$prefix/bin`.
Why's that? The `ocamldebug` session inherits the pwd of the bytecode file you pass as argument. In particular, breakpoints bring you to the proper file if you use the root `ocamlc`, and would bring you to the copied file in the `_build` directory if you used the `$prefix/bin` `ocamlc.byte`. (Well, actually, emacs would prompt you and bring you to the proper file, but it was a disruptive workflow.)
=> A better place to generate the `ocamlc` you use in a debug session

typing/typecore.ml
As we observed, such functions can be constructed by a ppx.
It's kind of a pain to write a test case for this, so I haven't, but I could if it seems necessary.
=> Functions with no clauses aren't local-returning

testsuite/tests/typing-layouts/or_null.ml
This covers the addition of `or_null`, which comprises v3 of the unboxed-types plan. This test is skipped (and so can be merged now), but someone should review this, as it is intended to include the entire specification for the `or_null` feature.
=> Unboxed types version 3 tests

typing/env.ml, typing/env.mli, typing/envaux.ml
I'm considering using this information in Js_of_ocaml to generate better code when supporting effect handlers.
But it makes a lot of sense to include it in `Env.summary` in any case.
=> Include the modes of values in debugging information

configure, configure.ac, runtime4/Makefile, runtime4/caml/config.h, runtime4/caml/dune, runtime4/dune, utils/domainstate.ml.c, utils/dune
This PR tweaks the dune files so that the following two targets now build (the latter, with a suitable ocamlopt on PATH):
```
dune b --workspace=duneconf/boot.ws _build/default/.ocamlcommon.objs/native/domainstate.cmx
dune b --workspace=duneconf/runtime_stdlib.ws _build/runtime_stdlib/runtime4/libasmrun.a
```
There is also a tweak to configure.ac to re-enable stack overflow detection (which is done in a different way on the ocaml 5 runtime)
=> Ocaml 5 runtime and configure tweaks

stdlib/atomic.mli, stdlib/bigarray.mli, stdlib/buffer.mli, stdlib/float.mli, stdlib/gc.ml, stdlib/gc.mli, stdlib/hashtbl.mli, stdlib/in_channel.mli, stdlib/int32.mli, stdlib/int64.mli, stdlib/map.mli, stdlib/moreLabels.mli, stdlib/nativeint.mli, stdlib/obj.mli, stdlib/oo.mli, stdlib/out_channel.mli, stdlib/random.mli, stdlib/seq.mli, stdlib/set.mli, stdlib/stdlib.mli, stdlib/templates/float.template.mli, stdlib/templates/hashtbl.template.mli, stdlib/templates/map.template.mli, stdlib/templates/set.template.mli
Resolve conflicts in stdlib mlis. These are almost always resolutions that prefer `tip-5`, but a handful of cases incorporate comments/documentation from `tip-jst`.
I make one update to `gc.ml` because, while we're still using the ocaml 4 runtime, we don't have to replace these functions with no-ops. When we finish merging the ocaml 5 runtime, we'll be flagged that these external functions don't exist and can figure out that they should be replaced with no-ops then.
Testing:
```
for x in stdlib/*.mli; do
file=$(basename ${x%.mli});
if echo $file | grep 'camlinternal\|stdlib\|std_exit'; then
cmi=$file
else
cmi=stdlib__${file^}
fi
dune b --workspace=duneconf/runtime_stdlib.ws _build/runtime_stdlib/stdlib/.stdlib.objs/byte/$cmi.cmi
done
```
You'll see some syntax errors for JS-internal …
=> Fix stdlib mlis

lambda/lambda.mli
Pulls out the `lambda.mli` piece of #171 so we can merge it and unblock middle-end/backend work. 
Testing: I've used this mli in a bunch of stacked PRs in order to confirm that things build. (See e.g. #179 )
=> OCaml 5 merge: Fix conflicts in lambda.mli

lambda/switch.ml, lambda/translattribute.ml, lambda/translclass.ml, lambda/translmod.ml, lambda/translobj.ml, lambda/translprim.ml
Finish off what #179 and #171 started.
Notable resolutions:
* As explained in #179, there's a new field on `Pfield`. An unresolved thread on that PR is also relevant here: Should accessing a module field be `Reads_vary` like it is upstream? I've asked Mark to weigh in.
* `Lambda.lfunction` was made a private type with a smart constructor both internally and upstream, and we have some extra arguments (region, mode). These are trivial to resolve.
* Two small diffs that we pull in from: https://github.com/ocaml-flambda/flambda-backend/pull/871
* explains diff in `translmod.ml` where we don't need `is_compilation_unit`
* explains diff in `translprim.ml` for `add_used_primtive` (where a change made upstream is irrelevant for us)
* Hardcoded checks for misplaced attribute warning go away …
=> Translation: resolve conflicts in remaining files (`translmod`, `transclass`, `translobj`, `translprim`, `translattribute`, `switch`)

.github/workflows/jane_ocaml5.yml, jane/build-resolved-files-for-ci
Add two things:
* A script that tries to build individual ml/mli files. The intention is that you can edit it in your PR to (1) provide evidence to your reviewer that your changes work, and (2) preserve that evidence for future runners of the script.
* A CI job that runs the script.
I think the first thing is very useful and the second thing is marginally useful.
Rigging up CI was tricky because it requires menhir in addition to the dune/OCaml setup from existing CI jobs.
The builds of these things (OCaml, dune, menhir) are cached, so it should take less than a minute per CI run. (See [this run](https://github.com/ocaml-flambda/ocaml-jst/actions/runs/6580127292/job/17877459123) for evidence of the caching.)
But, if we find that the CI job takes too long to run and is blocking merging, I …
=> Build OCaml 5 files in CI

asmcomp/mach.mli, bytecomp/bytelink.mli, middle_end/flambda/flambda_utils.mli, ocamltest/ocamltest_config.mli, otherlibs/systhreads/thread.mli, toplevel/topcommon.mli
Finish resolving all mli conflicts. I'm not sure if anyone is blocked on these files in particular, but it's nice to just be done resolving mlis so almost everything can be built.
Testing:
I couldn't test `toplevel/topcommon.mli`, `otherlibs/systhreads/thread.mli`, or `ocamltest/ocamltest_config.ml`, as these are built with another dune profile that relies on the compiler being able to build the stdlib. I think the conflict resolutions are simple enough that we should just merge them as-is.
```
$ dune b --workspace=duneconf/boot.ws _build/default/.ocamloptcomp.objs/byte/mach.cmi
$ dune b --workspace=duneconf/boot.ws _build/default/.ocamlbytecomp.objs/byte/bytelink.cmi
$ dune b --workspace=duneconf/boot.ws _build/default/.ocamloptcomp.objs/byte/flambda_utils.cmi
```
=> OCaml 5: resolve remaining mli conflicts

jane/build-resolved-files-for-ci, typing/tast_iterator.ml, typing/tast_iterator.mli, typing/tast_mapper.ml, typing/tast_mapper.mli
One thing to consider: Upstream added the ability to iterate over locations and attributes.  So, anywhere we've added something to the typed tree that contains locations or attributes, we must add a call to the appropriate iterators.  I think the only such places are in comprehensions.
Reviewer: @lpw25
=> OCaml5 merge conflicts in `tast_{mapper/iterator}.ml`

jane/build-resolved-files-for-ci, lambda/lambda.ml, lambda/printlambda.ml, lambda/simplif.ml, lambda/tmc.ml
This was originally #171, but rebased to remove lambda.mli, which was done separately in #183.
@mshinwell is the author of this code, not me.
=> Resolve conflicts in Lambda, Printlambda, Simplif, and Tmc

jane/build-resolved-files-for-ci, typing/ctype.ml, typing/ctype.mli, typing/includemod.ml, typing/includemod.mli
A couple small things to pay attention to in `includemod`:
- Some code (particularly `equate_one_functor_param`) was factored out in [an upstream PR](https://github.com/ocaml/ocaml/pull/12063) such that the two call sites in our code were had differing opinions about whether they were looking at `Lazy` versions of things or not.  I made a small change in `Functor_inclusion_diff.update` to make these line up, but didn't think much about where we do and don't want to preserve laziness.
- The `Includemod.signature_symptom` type has had more information added to it in a way that is inconvenient because we can no longer use the same exact type for normal signature mismatches and include functor ones.  The new information doesn't actually have any uses in the compiler, I suppose it must be used …
=> Fix ocaml5 merge conflicts in `ctype` and `includemod`

lambda/matching.ml, lambda/switch.ml, lambda/translattribute.ml, lambda/translclass.ml, lambda/translcore.ml, lambda/translmod.ml, lambda/translobj.ml, lambda/translprim.ml
Cherry-picks a commit from #171; once that's merged I'll drop the `lambda.ml` and `lambda.mli` changes from here.
Nature of the resolutions:
* (~60% of the conflicts) Upstream added an argument `Immediate | Pointer` to `Pfield` in addition to `mutable_flag`. We added `field_read_semantics` internally (this is semantically equivalent to `mutable_flag`, though the constructor names are different). The conflicts are easy to resolve: I just figure out `immediate_or_pointer` based on the upstream piece of the diff.
* (~3 conflicts) Lazy field accesses are factored out to a function upstream; I add an extra argument to this function because we populated `ap_inlined` differently at one callsite (though I doubt it actually matters, as I explain in a comment).
* The rest mostly have to do with …
=> Translation: Resolve conflicts in `matching.ml` and `translcore.ml`

jane/build-resolved-files-for-ci, lambda/transl_array_comprehension.ml
Adds `lambda/*.ml` to the build script, and fix a build error relating to that. I forgot to in #179, which predated the CI.
The only one I have to exempt is `matching.ml` because it relies on `Obj.forcing_tag` in the stdlib.
Review: @mshinwell ?
=> Add lambda mls to build script and ci

bytecomp/bytegen.ml, bytecomp/bytelink.ml, bytecomp/bytelink.mli, bytecomp/bytepackager.ml, bytecomp/emitcode.ml, bytecomp/symtable.ml, jane/build-resolved-files-for-ci
@lukemaurer please could you review this, and check carefully - it's likely I've made mistakes here.  One thing you might want to do is to diff the files on this branch directly from the `tip-5` tag, rather than looking directly at this PR's diff.  This shows our changes compared to upstream OCaml 5, so that diff should kind of look like the original symbols patch (plus some other minor modifications for other bytecode files which should be straightforward).  Unfortunately there were changes in OCaml 5 regarding the relocation processing, although it now seems to me that maybe they don't matter too much, since we don't need the renaming of relocations any more (iirc)?
=> Resolving conflicts in bytecomp/

file_formats/cmi_format.ml, file_formats/cmt_format.ml, jane/build-resolved-files-for-ci
This also makes the necessary changes required for the OCaml 4 runtime, namely that compressed marshalling is not supported.
=> Resolve conflicts in file_formats/

jane/build-resolved-files-for-ci, typing/env.ml, typing/typetexp.ml
Nothing particularly notable.
- Most `typetexp` conflicts are due to upstream refactors that have been half backported (plus modes).
- Most `env` conflicts are due to laziness changes on lines where we also backported shape changes.
Review: @lpw25
=> OCaml5 merge conflicts: `typing/{env,typetexp}.ml`

.gitignore, jane/conflicts, stdlib/.depend
Pierre's PRs made me realize I'd forgotten about `stdlib/.depend`. This PR resolves those conflicts, fixes `jane/conflicts` to look in hidden files, and fixes `.gitignore` as well.
=> OCaml5: resolve conflicts in hidden files

jane/build-resolved-files-for-ci, typing/typeclass.ml, typing/typedecl.ml
Not much notable here.  Some annoying conflicts in typedecl caused by a couple upstream PRs which we backported but were then built on a bit more upstream.
Review: @lpw25
=> OCaml5 conflicts: typedecl and typeclass

jane/build-resolved-files-for-ci, ocamldoc/.depend, ocamldoc/Makefile
Resolve the conflicts in OCamldoc. 
They were limited to Makefile / .depend -- an even if I thought this Makefile got merged with the main Makefile in OCaml 5 the commit actually doing it was done after the 5.1 tagging
=> Resolve conflicts in ocamldoc

driver/optcompile.ml
For some reason this file can't be built by the script or using the recommended command line invocation, but it does get built while moving further down the path of building the whole compiler, which is how I noticed this issue.
=> Fix for optcompile

otherlibs/systhreads/st_stubs.c
Created in discussion with @mshinwell .
Use the `tip-jst` version of `st_stubs.c`. The changes in `tip-5` must come in lockstep with changes in the runtime. (`st_stubs.c` is part of the runtime, in a manner of thinking.)
Created with: `git checkout tip-jst otherlibs/systhreads/st_stubs.c`. Then I added a comment reminding us to look at this when we update the runtime.
=> OCaml 5: use `tip-jst` for `otherlibs/systhreads/st_stubs.c`

testsuite/tests/c-api/test_c_thread_has_lock.ml, testsuite/tests/c-api/test_c_thread_has_lock_systhread.ml, testsuite/tests/callback/callback_effects_gc.ml, testsuite/tests/effects/marshal.ml, testsuite/tests/frame-pointers/c_call.ml, testsuite/tests/frame-pointers/effects.ml, testsuite/tests/frame-pointers/exception_handler.ml, testsuite/tests/frame-pointers/reperform.ml, testsuite/tests/frame-pointers/stack_realloc.ml, testsuite/tests/frame-pointers/stack_realloc2.ml, testsuite/tests/lib-bigarray/bigarrays.ml, testsuite/tests/lib-channels/close_in.ml, testsuite/tests/lib-channels/refcounting.ml, testsuite/tests/lib-format/domains.ml, testsuite/tests/lib-random/parallel.ml, testsuite/tests/lib-runtime-events/test_caml_counters.ml, testsuite/tests/lib-runtime-events/test_caml_runparams.ml, testsuite/tests/lib-runtime-events/test_dropped_events.ml, testsuite/tests/lib-runtime-events/test_external_preserve.ml, testsuite/tests/lib-runtime-events/test_user_event.ml, testsuite/tests/lib-runtime-events/test_user_event_unknown.ml, testsuite/tests/lib-systhreads/boundscheck.ml, testsuite/tests/memory-model/forbidden.ml, testsuite/tests/memory-model/publish.ml, testsuite/tests/parallel/domain_parallel_spawn_burn_gc_set.ml, testsuite/tests/parallel/recommended_domain_count.ml, testsuite/tests/parallel/recommended_domain_count_unix.ml, testsuite/tests/parallel/test_issue_11094.ml, testsuite/tests/weak-ephe-final/weaktest_par_load.ml
Reviewer: @mshinwell ?
Cherry-pick commits from https://github.com/dra27/ocaml for disabling tests that rely on the OCaml 5 runtime.
=> OCaml 5 on 4: testsuite changes

stdlib/StdlibModules, stdlib/camlinternalLazy.ml, stdlib/camlinternalLazy.mli, stdlib/filename.ml, stdlib/format.ml, stdlib/format.mli, stdlib/hashtbl.ml, stdlib/lazy.ml, stdlib/random.ml, stdlib/stdlib.ml, stdlib/stdlib.mli
Backport the pieces of https://github.com/dra27/ocaml/commit/46aea8c92445a0d7e77db8223b53b83d48fa94c3 that touch files under `stdlib/`. This was done almost entirely by copying-and-pasting from the diff for that commit, as ~everything conflicted.
Backported code is delimited by `BACKPORT BEGIN`/`BACKPORT END` blocks, as in the patch, but I also add a "CR ocaml 5 runtime" needle as we've used elsewhere:
```
(* CR ocaml 5 runtime:
BACKPORT BEGIN
<tip-5 code>
*)
<backported code>
(* BACKPORT END *)
```
When code is just commented out and nothing is added in its lieu, that looks like:
```
(* CR ocaml 5 runtime:
BACKPORT
<tip-5 code>
*)
```
=> OCaml 5 on 4 runtime: Backport stdlib pieces of 46aea8c924

bytecomp/dll.ml, debugger/debugcom.ml, debugger/debugcom.mli, debugger/frames.ml, debugger/time_travel.ml
```
d35a2bfb18 [BACKPORT] Adapt to 4.14 runtime
bytecomp/dll.ml | 8 ++++++++
1 file changed, 8 insertions(+)
4e8d83046b [BACKPORT] Adapt to 4.14 runtime
debugger/debugcom.ml    | 58 +++++++++++++++++++++++++++++++++++++++++++++++++
debugger/debugcom.mli   |  4 ++++
debugger/frames.ml      |  8 +++++++
debugger/time_travel.ml | 22 +++++++++++++++++++
4 files changed, 92 insertions(+)
```
These were cherry-picked verbatim from David Allsopp's repo.
There is also a fix to the temporary build script so it works on the bash provided with macOS.
=> OCaml 5 on runtime4: bytecomp and debugger

jane/build-resolved-files-for-ci, lambda/matching.ml, stdlib/lazy.ml
This just wholesale replaces the implementation rather than using the approach from the backports changesets of commenting out specific sections, which was complicated to look at.  I copy/pasted the 4.x implementation from flambda-backend.
=> OCaml 5 on runtime4: use 4.x lazy implementation

asmcomp/amd64/emit.mlp, asmcomp/amd64/proc.ml, asmcomp/arm64/emit.mlp, asmcomp/asmlink.ml, asmcomp/cmm_helpers.ml, asmcomp/cmmgen.ml, otherlibs/dynlink/native/dynlink.ml, testsuite/tests/asmcomp/polling.c, testsuite/tests/backtrace/backtrace_dynlink.flambda.reference, testsuite/tests/backtrace/backtrace_dynlink.reference, testsuite/tests/effects/unhandled_unlinked.ml, testsuite/tests/lib-dynlink-initializers/test10_main.native.reference, testsuite/tests/tsan/array_elt.ml, testsuite/tests/tsan/exn_from_c.ml, testsuite/tests/tsan/exn_in_callback.ml, testsuite/tests/tsan/exn_reraise.ml, testsuite/tests/tsan/handlers_at_tail.ml, testsuite/tests/tsan/norace_atomics.ml, testsuite/tests/tsan/perform.ml, testsuite/tests/tsan/raise_through_handler.ml, testsuite/tests/tsan/record_field.ml, testsuite/tests/tsan/reperform.ml
(called "backend and lambda" in the internal list, but that is a bit misleading).
This does not include replacing the implementation of "lazy" in matching.ml with the OCaml 4 version.  A separate PR is coming for that.
The changeset that mentions a bootstrap no longer includes one.
=> OCaml 5 on runtime4: asmcomp/ changes + a few others

runtime4/caml/exec.h
The exec magic number in `runtime4/caml/exec.h` was out of sync with the (updated) one elsewhere.
=> Fix magic number

runtime4/dune, runtime4/gen_primitives.sh, runtime4/misc.c, stdlib/random.ml
The 5.x `Random` module uses a new PRNG.  I've copied this into `runtime4/misc.c`.  I think this is reasonable even though we are using the 4.x runtime for 5-minus.
=> Fixes for Stdlib.Random

asmcomp/cmm_helpers.ml
This got missed, it was part of the backport commit `46aea8c92445a0d7e77db8223b53b83d48fa94c3` (from David's repo).
=> OCaml 5 on runtime4: Minor Cmm_helpers fix

stdlib/string.ml, stdlib/string.mli, stdlib/stringLabels.mli, stdlib/sys.ml.in, stdlib/sys.mli
The interface changes don't affect any functions that were present in the Stdlib in 4.x, so this should be ok.
=> Minor String and Sys fixes for runtime functionality not available in 4.x

ocamltest/builtin_actions.ml
Something looks to have previously deleted the naked pointers test here during our recent work, but I think we should probably keep it for now, since naked pointers are still permitted in 4.x.
=> Fixes to builtin_actions.ml

asmcomp/amd64/proc.ml
This was also missed from `46aea8c92445a0d7e77db8223b53b83d48fa94c3`.  This version is slightly different from that backport commit, but clearer I think.
=> Fix Proc.destroyed_at_c_call for amd64

typing/printtyp.ml
In upstream [#11888](https://github.com/ocaml/ocaml/pull/11888), a call to `Names.with_local_names` in `Printtyp` moved from `tree_of_constructor` to `tree_of_constructor_in_decl`.  We had already moved this call to `tree_of_constructor_args_and_ret_type`, and in the merge we ended up with both calls.  This keeps the upstream one and delete the other.
This was causing test failures like [this one](https://github.com/ocaml-flambda/ocaml-jst/pull/228/files#diff-89a24f971ec4b19a438c28c349f2f982d6264b416798b5390bad230a35f3939aL200)
Review: @goldfirere
=> OCaml5 merge: fix name issue in printtyp

testsuite/tests/backtrace/backtrace_effects_nested.ml, testsuite/tests/callback/nested_fiber.ml, testsuite/tests/callback/stack_overflow.ml, testsuite/tests/callback/test7.ml, testsuite/tests/lazy/lazy2.ml, testsuite/tests/lazy/lazy3.ml, testsuite/tests/lazy/lazy5.ml, testsuite/tests/lazy/lazy6.ml, testsuite/tests/lazy/lazy7.ml, testsuite/tests/lazy/lazy8.ml, testsuite/tests/lib-runtime-events/test_external.ml, testsuite/tests/lib-runtime-events/test_fork.ml, testsuite/tests/lib-runtime-events/test_instrumented.ml, testsuite/tests/lib-sync/trylock.ml, testsuite/tests/lib-sync/trylock2.ml
Several of these had improper `* skip` ocamltest directives, so I fixed those. Others were just not disabled, even though they were added in OCaml 5 and use the new stdlib modules &mdash; I disabled those.
=> Skip tests added in `tip-5` involving new modules (`Effect`/`Domain`/`Atomic`/...)

debugger/loadprinter.ml
The debugger checks that an installed printer's type matches the expected scheme. Pierre rightly pointed out in review of #199 that we might want `Env.initial` on this line instead of `Env.empty`. I thought that ocaml/ocaml#11745 obviated this, but I was wrong.
Indeed, the change from `Env.empty` to `Env.initial` was done internally, in preparation for unboxed types: https://github.com/ocaml/ocaml/pull/11745/files#diff-ba1ff056eac914a52442c6f08f0562daabc8d8520748120f4cf0308391a59802
Review suggestion: @ccasin 
This fixes test `testsuite/tool-debugger/printer/debuggee.ml`. Without this change you get the output:
```
> +Printer.p has the wrong type for a printing function.
>  Loading program... done.
>  Breakpoint: 1
>  18   <|b|>for _i = 0 to x do
> -x: int = S S O
> +x: int = 3
``` …
=> OCaml 5: one-line change to fix debugger env for testsuite

testsuite/tests/language-extensions/language_extensions.ml, testsuite/tests/language-extensions/pprintast_unconditional.ml
This one's straightforward.
```
make -f Makefile.jst install_for_test
make -f Makefile.jst test-one-no-rebuild DIR=language-extensions
```
=> OCaml 5: Fix simple compile errors in language extensions tests

parsing/parser.mly, testsuite/tests/parsetree/locations_test.compilers.reference, testsuite/tests/typing-layouts/annots_beta.ml
This fixes [typing-gadts/test.ml](https://github.com/ocaml-flambda/ocaml-jst/pull/228/files#diff-9806dee4a84e77cbd79cba5141ffb88fb80eb8be71f8faa9a38a7b241d33ca0e)
We're parsing type constraints on let bindings a little differently than upstream when they contain locally abstract types (e.g., `let x : type a . a = ...`).  Upstream 5.1 gives the `core_type` node for the annotation a different (probably better) location than it used to, and this simply matches that.
Two other tests are promoted because they contain similar locations:
```
parsetree/locations_test.compilers.reference
typing-layouts/annots_beta.ml
```
In the former case the test also exists upstream, and after this PR we now match the upstream behavior.
Reviewer: @ncik-roberts
=> Adjust location to match upstream for consistent errors

testsuite/tests/gc-roots/globroots.ml, testsuite/tests/gc-roots/globroots_parallel.ml, testsuite/tests/gc-roots/globroots_parallel_spawn_burn.ml, testsuite/tests/gc-roots/globrootsprim.c, testsuite/tests/lazy/minor_major_force.ml, testsuite/tests/lf_skiplist/test.ml, testsuite/tests/lf_skiplist/test_parallel.ml, testsuite/tests/regression/pr9326/gc_set.ml
Rework/disable pieces of tests that only work in OCaml 5.
* `lf_skiplist`: disable, this uses some a new C module added in the 5 runtime.
* `globroots.ml`: disable the parallel ones, keep the sequential one (and comment out the use of `Domain` in the sequential one)
* `lazy/major_minor_force.ml`: skip, this was added in OCaml 5 and relies on the new implementation of lazy
* `regression/pr9326/gc_set.ml`: revert to the `tip-jst` version for now, as different GC control fields are settable in the 5 runtime vs. the 4 runtime (and this test just checks which fields are settable)
suggested reviewer: @xclerc
=> OCaml 5: rework some OCaml-5-only tests

jane/build-resolved-files-for-ci, typing/jkind.ml, typing/typeclass.ml, typing/typecore.mli, typing/uniqueness_analysis.ml
These files didn't have conflicts, so the errors didn't show up until I tried to build everything.
This includes a change in `typecore.mli` that is also present in the `typecore` PR, needed to fix an issue in `typeclass.ml`.
=> Misc build errors in typing

testsuite/tests/effects/issue479.ml, testsuite/tests/lib-str/parallel.ml, testsuite/tests/lib-systhreads/multicore_lifecycle.ml, testsuite/tests/lib-unix/common/multicore_fork_domain_alone.ml, testsuite/tests/lib-unix/common/multicore_fork_domain_alone2.ml, testsuite/tests/parallel/backup_thread.ml, testsuite/tests/parallel/backup_thread_pipe.ml, testsuite/tests/parallel/domain_serial_spawn_burn.ml, testsuite/tests/parallel/fib_threads.ml, testsuite/tests/parallel/major_gc_wait_backup.ml, testsuite/tests/parallel/mctest.ml, testsuite/tests/parallel/multicore_systhreads.ml, testsuite/tests/parallel/poll.ml, testsuite/tests/parallel/test_c_thread_register.ml
Some tests were failing because asterisks weren't well-nested. This PR fixes them.
=> OCaml5: fix typos in skip directives

testsuite/tests/backtrace/backtrace_c_exn.byte.reference, testsuite/tests/backtrace/backtrace_c_exn.ml, testsuite/tests/backtrace/backtrace_c_exn.opt.reference, testsuite/tests/backtrace/backtrace_c_exn.reference
Rework a test to allow for different backtraces in bytecode vs. native code when a C function calls an OCaml function that raises an exception.
I confirmed that this test behaves identically at the head of flambda-backed. (by copying the test and running it there.) So this difference doesn't seem like anything introduced by the merge.
Testing:
```
$ make -f Makefile.jst install_for_test; make -f Makefile.jst test-one-no-rebuild TEST=backtrace/backtrace_c_exn.ml
```
=> OCaml 5: fix backtraces in C exn test

typing/ctype.ml
(This is the same as #261, which was closed when I accidentally messed with the history).
OCaml 4 had a function `Ctype.nongen_schema`, which is one of the places we remove mode variables.  That function was replaced by `Ctype.nongen_vars_in_schema` in [upstream #12051](https://github.com/ocaml/ocaml/pull/12051) so I copied the defaulting there.  But there is another change in that PR, which is that some functions which used to call `Ctype.nongen_schema` don't call `nongen_vars_in_schema` - instead they call a lower-level function used in its implementation, `add_nongen_vars_in_schema`.  So the defaulting should go there, and this PR moves it.
This fixes `typing-local/regression_class_type.ml`.
Review: @lpw25 (or whoever feels like it)
=> OCaml5 merge: Fix ctype var defaulting

typing/typecore.ml
This fixes the test failure in `typing-poly/poly.ml`.
`Typecore.check_univars` checks that variables meant to be polymorphic haven't been instantiated by unification.  Way back in the first unboxed type PR, `check_univars` was reworked to also make sure sort variables also don't get inappropriately instantiated.  At the same time I added that check, I made it so we fail earlier in some cases where the old error could be issued, just because it was easy to do so.  But upstream has added a test that reveals this difference, and there's no particularly good reason to worry about issuing this type error as fast as possible, so let's not.
review: @lpw25 (or anyone else so inclined)
=> OCaml 5: match upstream behavior in `check_univars`
